# --- 1. CONFIGMAP (Konfigurasi Umum) ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stockly-config
data:
  DB_HOST: "db-service"
  DB_USER: "root"

---
# --- 2. SECRET (Password Database) ---
apiVersion: v1
kind: Secret
metadata:
  name: stockly-secret
type: Opaque
data:
  # Password: admin123
  DB_PASSWORD: YWRtaW4xMjM=

---
# --- 3. DATABASE (MySQL) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockly-db
spec:
  selector:
    matchLabels:
      app: stockly
      component: database
  template:
    metadata:
      labels:
        app: stockly
        component: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stockly-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: stockly
    component: database
  ports:
    - port: 3306
---
# --- 4. BACKEND: INVENTORY ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: stockly
      component: inventory
  template:
    metadata:
      labels:
        app: stockly
        component: inventory
    spec:
      containers:
      - name: inventory
        image: stockly-inventory:v1
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: stockly-config
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stockly-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: stockly
    component: inventory
  ports:
    - port: 5001
---
# --- 5. BACKEND: PRODUCT ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: stockly
      component: product
  template:
    metadata:
      labels:
        app: stockly
        component: product
    spec:
      containers:
      - name: product
        image: stockly-product:v1 
        imagePullPolicy: Never 
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: stockly-config
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stockly-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: stockly
    component: product
  ports:
    - port: 5002 
---
# --- 6. BACKEND: OPERASIONAL ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operasional-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stockly
      component: operasional
  template:
    metadata:
      labels:
        app: stockly
        component: operasional
    spec:
      containers:
      - name: operasional
        image: stockly-operasional:v1
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: stockly-config
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stockly-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: operasional-service
spec:
  selector:
    app: stockly
    component: operasional
  ports:
    - port: 5003
    
---
# --- 7. FRONTEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockly
      component: frontend
  template:
    metadata:
      labels:
        app: stockly
        component: frontend
    spec:
      containers:
      - name: frontend
        image: stockly-frontend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort 
  selector:
    app: stockly
    component: frontend
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30005