# --- 1. CONFIGMAP (Konfigurasi Umum) ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stockly-config
data:
  DB_HOST: "db-service"
  DB_USER: "root"

---
# --- 2. SECRET (Password Database) ---
apiVersion: v1
kind: Secret
metadata:
  name: stockly-secret
type: Opaque
data:
  # Password: admin123
  DB_PASSWORD: YWRtaW4xMjM=

---
# --- 3. DATABASE (MySQL) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockly-db
spec:
  selector:
    matchLabels:
      app: stockly
      component: database
  template:
    metadata:
      labels:
        app: stockly
        component: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stockly-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: stockly
    component: database
  ports:
    - port: 3306

# --- 4. BACKEND: INVENTORY ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: stockly
      component: inventory
  template:
    metadata:
      labels:
        app: stockly
        component: inventory
    spec:
      containers:
      - name: inventory
        image: stockly-inventory:v1
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: stockly-config
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stockly-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: stockly
    component: inventory
  ports:
    - port: 5001